### ISSUE TITLE
Duotone background Images?

### ISSUE THREAD

**Issue by lentilz** [fabricelejeune/jquery-duotone#1]
Is it possible to apply this on inlined background images?

**Comment by josephcoombes** [comment]
Wondering about background images as well. Thanks!

**Comment by lentilz** [comment]
Hey @josephcoombes a couple options here:
If youre using this plugin, I was able to style the inline image as a background by using object-fit https://css-tricks.com/almanac/properties/o/object-fit/

Object-fit turned out to be more of a hack for my use case and was seeing some images still being stretched out so I opted to do this via svg filters instead. Was a bit of a learning curve but I created a pen that you can reference for how this works. http://codepen.io/lentilz/pen/mPOKdG

Hope it helps!

**Comment by josephcoombes** [comment]
Awesome! Thanks for your help. Your Codepen looks great btw. Looking forward to digging in here.
